let
    Source = Sql.Database("SL000113.one.ad,60001", "KITFOLLOWUP_PRD", [Query="SELECT#(lf)  Table__224.JOBCARDHEADER_NUMBER,#(lf)  cast(cast(Table__224.JOBCARDHEADER_CREATEDATE AS DATE) as datetime),#(lf)  dbo.SITE.SITE_LABEL,#(lf)  Table__224.JOBCARDHEADER_AIRCRAFTNUMBER,#(lf)  HARNESS_Jobcard.HARNESS_CODE,#(lf)  dbo.PREPARATION.PREPARATION_REALTIME,#(lf)  HARNESS_MNGMT_PROGRAM.PROGRAM_LABEL,#(lf)  Aircraft_location.SITE_LABEL,#(lf)  dbo.JOBCARDHEADER_HARNESS_XREF.JOBCARDHEADER_HARNESS_XREF_SERIALNUMBER,#(lf)  Table__224.JOBCARDHEADER_PREPDESCRIPTION,#(lf)  IMPUTATION.CODEVALUE_LABELFR,#(lf)  dbo.LASTCOMMENTView.COMMENT_LABEL,#(lf)  Installation_Site.SITE_LABEL,#(lf)  dbo.DOCUMENT.DOCUMENT_REFERENCE,#(lf)  dbo.DOCUMENT.DOCUMENT_TYPE,#(lf)  dbo.LASTSTATUSView.STATUS_LABELFR,#(lf)  LTRIM(RTRIM(MAJOR_DOC_TYPE.CODEVALUE_LABELFR)),#(lf)  Preparation_User.KFUUSER_FULLNAME,#(lf)  cast (CAST(DELIVERY_PROD_CUSTLABS.DELIVERY_SENDINGDATE AS DATE) as datetime),#(lf)  cast(cast(Table__224.JOBCARDHEADER_GOALDATE AS DATE) as datetime),#(lf)  cast(cast(Table__224.JOBCARDHEADER_FORECASTDATE AS DATE) as datetime),#(lf)  Table__224.JOBCARDHEADER_CATEGORIZATION,#(lf)  dbo.LASTSTATUSView.LOGSTATUS_CREATEDATE,#(lf)  cast(cast( dbo.LASTSTATUSView.LOGSTATUS_CREATEDATE AS DATE) as datetime),#(lf)  dbo.PROGRESS.PROGRESS_PROGPROD,#(lf)  dbo.View_JOBCARD_MAJOR_DOC.DOC_REF1,#(lf)  SYSDATETIMEOFFSET() AS ExtractionDateTime#(lf)FROM#(lf)  ((((((((((((((((((( SELECT dbo.JOBCARDHEADER.*, dbo.PROGRAM.PROGRAM_MILITARY as JobcardMilitaryRigts#(lf)FROM dbo.JOBCARDHEADER left outer join dbo.PROGRAM on dbo.PROGRAM.PROGRAM_ID=dbo.JOBCARDHEADER.JOBCARDHEADER_PROGRAM#(lf)WHERE (dbo.JOBCARDHEADER.JOBCARDHEADER_ACTIVE = 1)) Table__224 LEFT OUTER JOIN dbo.SITE ON (dbo.SITE.SITE_ID=Table__224.JOBCARDHEADER_CREATESITE) ) RIGHT OUTER JOIN dbo.DOCUMENT ON (Table__224.JOBCARDHEADER_ID=dbo.DOCUMENT.DOCUMENT_JOBCARDHEADER) ) LEFT OUTER JOIN dbo.LASTSTATUSView ON (dbo.LASTSTATUSView.LOGSTATUS_JOBCARD=Table__224.JOBCARDHEADER_ID) ) LEFT OUTER JOIN dbo.PREPARATION ON (Table__224.JOBCARDHEADER_ID=dbo.PREPARATION.PREPARATION_JOBCARDHEADER and Table__224.JOBCARDHEADER_ACTIVE=dbo.PREPARATION.PREPARATION_ACTIVE) ) LEFT OUTER JOIN dbo.SITE  Installation_Site ON (Installation_Site.SITE_ID=Table__224.JOBCARDHEADER_INSTALPLANT) ) FULL OUTER JOIN dbo.KFUUSER  Preparation_User ON (Preparation_User.KFUUSER_ID=Table__224.JOBCARDHEADER_PREPARUSER) ) LEFT OUTER JOIN dbo.PROGRESS ON (Table__224.JOBCARDHEADER_ID=dbo.PROGRESS.PROGRESS_JOBCARDHEADER) ) LEFT OUTER JOIN dbo.LASTCOMMENTView ON (dbo.LASTCOMMENTView.COMMENT_JOBCARDHEADER=Table__224.JOBCARDHEADER_ID) ) FULL OUTER JOIN dbo.CODEVALUE  IMPUTATION ON (Table__224.JOBCARDHEADER_IMPUTATION=IMPUTATION.CODEVALUE_VALUE and IMPUTATION.CODEVALUE_CODE='IMPUTATION') ) FULL OUTER JOIN dbo.SITE  Aircraft_location ON (Aircraft_location.SITE_ID=Table__224.JOBCARDHEADER_ACLOCATION) ) LEFT OUTER JOIN dbo.MAJORDOCUMENTGroupByJOBCARDView ON (Table__224.JOBCARDHEADER_ID=dbo.MAJORDOCUMENTGroupByJOBCARDView.DOCUMENT_JOBCARDHEADER) )#(lf)   LEFT OUTER JOIN dbo.CODEVALUE  MAJOR_DOC_TYPE ON (dbo.MAJORDOCUMENTGroupByJOBCARDView.DOCUMENT_TYPE = MAJOR_DOC_TYPE.CODEVALUE_VALUE  and MAJOR_DOC_TYPE.CODEVALUE_CODE='TYPEDOC') ) FULL OUTER JOIN dbo.JOBCARDHEADER_HARNESS_XREF ON (Table__224.JOBCARDHEADER_ID=dbo.JOBCARDHEADER_HARNESS_XREF.JOBCARDHEADER_HARNESS_XREF_JOBCARDHEADER and Table__224.JOBCARDHEADER_ACTIVE=dbo.JOBCARDHEADER_HARNESS_XREF.JOBCARDHEADER_HARNESS_XREF_ACTIVE) )#(lf)   LEFT OUTER JOIN dbo.HARNESS  HARNESS_Jobcard ON (HARNESS_Jobcard.HARNESS_ID=dbo.JOBCARDHEADER_HARNESS_XREF.JOBCARDHEADER_HARNESS_XREF_HARNESS) )#(lf)   LEFT OUTER JOIN dbo.I_SECTION  I_SECTION_HarnessJobc ON (HARNESS_Jobcard.HARNESS_I_SECTION = I_SECTION_HarnessJobc.I_SECTION_ID and I_SECTION_HarnessJobc.I_SECTION_ACTIVE=1) )#(lf)   LEFT OUTER JOIN dbo.PROGRAM  HARNESS_MNGMT_PROGRAM ON (HARNESS_MNGMT_PROGRAM.PROGRAM_ID=I_SECTION_HarnessJobc.I_SECTION_PROGRAM) ) LEFT OUTER JOIN dbo.View_JOBCARD_MAJOR_DOC ON (Table__224.JOBCARDHEADER_ID=dbo.View_JOBCARD_MAJOR_DOC.DOCUMENT_JOBCARDHEADER) ) LEFT OUTER JOIN ( select DELIVERY_ID, DELIVERY_JOBCARDHEADER, DELIVERY_STEP, DELIVERY_SENDINGSITE, DELIVERY_SENDINGDATE, #(lf)                      DELIVERY_RECEIVINGSITE, DELIVERY_RECEIVINGDATE, DELIVERY_RECEIVEUSER, DELIVERY_WITHMISSING, DELIVERY_SHIPPINGNUMBER, #(lf)                      DELIVERY_LAST_DELIVERY, DELIVERY_ACTIVE,#(lf)                      SENDING_SITE.SITE_ID as SENDING_SITE_ID, #(lf)SENDING_SITE.SITE_TYPESITE as SENDING_SITE_TYPESITE, #(lf)SENDING_SITE.SITE_CODE as SENDING_SITE_CODE, #(lf)SENDING_SITE.SITE_LABEL as SENDING_SITE_LABEL,#(lf)RECEIVING_SITE.SITE_ID as RECEIVING_SITE_ID, #(lf)RECEIVING_SITE.SITE_TYPESITE as RECEIVING_SITE_TYPESITE, #(lf)RECEIVING_SITE.SITE_CODE as RECEIVING_SITE_CODE, #(lf)RECEIVING_SITE.SITE_LABEL as RECEIVING_SITE_LABEL#(lf)from DELIVERY#(lf)inner join [SITE] as SENDING_SITE ON SENDING_SITE.SITE_ID = DELIVERY_SENDINGSITE and SENDING_SITE.SITE_TYPESITE='PROD'#(lf)inner join [SITE] as RECEIVING_SITE ON RECEIVING_SITE.SITE_ID = DELIVERY_RECEIVINGSITE and RECEIVING_SITE.SITE_TYPESITE in ('LABS','CUST')#(lf)WHERE DELIVERY_STEP=5) DELIVERY_PROD_CUSTLABS ON (Table__224.JOBCARDHEADER_ID=DELIVERY_PROD_CUSTLABS.DELIVERY_JOBCARDHEADER) )#(lf)WHERE#(lf)  ( #(lf)  HARNESS_MNGMT_PROGRAM.PROGRAM_LABEL  IN  ('A351', 'A353', 'A355', 'A356')#(lf)  AND  Table__224.JOBCARDHEADER_TYPE  NOT IN  ('LABS', 'M', 'SRM', 'W', 'WO')#(lf)  AND  LTRIM(RTRIM(dbo.LASTSTATUSView.STATUS_LABELEN))  NOT IN  ('D3 CLOSED', 'D2 Kit Cancelled', 'D3 AIRBUS CANCELLED', 'D3 CANCELLED', 'D2 Airbus Cancelled', 'D2 Cancelled concession')#(lf)  AND  cast(cast( dbo.LASTSTATUSView.LOGSTATUS_CREATEDATE AS DATE) as datetime)  >  cast(cast(DATEADD(""Year"",-1,CURRENT_TIMESTAMP) as datetime)as date)#(lf)  )"]),
    #"Colonnes renommées" = Table.RenameColumns(Source,{{"JOBCARDHEADER_NUMBER", "Jobcard Number"}, {"SITE_LABEL", "Creation site"}, {"", "Creation date (DD/MM/YYYY)"}, {"JOBCARDHEADER_AIRCRAFTNUMBER", "Aircraft number"}, {"HARNESS_CODE", "Harness"}, {"PREPARATION_REALTIME", "Preparation Realtime"}, {"PROGRAM_LABEL", "Harness program"}, {"SITE_LABEL2", "Aircraft location"}, {"JOBCARDHEADER_HARNESS_XREF_SERIALNUMBER", "Harness serial number"}, {"JOBCARDHEADER_PREPDESCRIPTION", "Preparation description"}, {"CODEVALUE_LABELFR", "Imputation FR (French translation)"}, {"COMMENT_LABEL", "Last comment"}, {"SITE_LABEL3", "Installation site"}, {"DOCUMENT_REFERENCE", "Reference"}, {"DOCUMENT_TYPE", "Type"}, {"STATUS_LABELFR", "Last Status (French)"}, {"2", "Trim Major document_Type (French)"}, {"KFUUSER_FULLNAME", "Fullname of Preparation user"}, {"5", "Update date of last status 2 (DD/MM/YYYY HH:MM:SS)"}, {"JOBCARDHEADER_CATEGORIZATION", "Category"}, {"LOGSTATUS_CREATEDATE", "Update date of last status (DD/MM/YYYY HH:MM:SS)"}, {"PROGRESS_PROGPROD", "Production progress (%)"}, {"DOC_REF1", "Reference major doc 1"}, {"3", "Delivery sending date PROD-) CUSTL2"}, {"4", "Goal Date"}}),
    #"Colonnes renommées1" = Table.RenameColumns(#"Colonnes renommées",{{"6", "Forecast date (DD/MM/YYYY)"}}),
    #"Colonnes supprimées" = Table.RemoveColumns(#"Colonnes renommées1",{"Update date of last status 2 (DD/MM/YYYY HH:MM:SS)"}),
    Arrondi = Table.TransformColumns(#"Colonnes supprimées",{{"Preparation Realtime", each Number.Round(_, 2), type number}}),
    #"Personnalisée ajoutée" = Table.AddColumn(Arrondi, "DansScope", each null),
    #"Colonnes permutées" = Table.ReorderColumns(#"Personnalisée ajoutée",{"Jobcard Number", "Type", "Trim Major document_Type (French)", "Creation date (DD/MM/YYYY)", "Creation site", "Fullname of Preparation user", "Harness program", "Harness serial number", "Aircraft number", "Harness", "Imputation FR (French translation)", "Preparation Realtime", "Aircraft location", "Preparation description", "Last comment", "Installation site", "Reference", "Last Status (French)", "Delivery sending date PROD-) CUSTL2", "Goal Date", "Forecast date (DD/MM/YYYY)", "Production progress (%)", "Category", "DansScope", "Update date of last status (DD/MM/YYYY HH:MM:SS)", "Reference major doc 1", "ExtractionDateTime"}),
    #"Type modifié1" = Table.TransformColumnTypes(#"Colonnes permutées",{{"ExtractionDateTime", type datetime}})
in
    #"Type modifié1"